#!/bin/sh

# $FreeBSD$
#
# PROVIDE: webhook
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
#################################################################################
# HackThisSite FreeBSD Helpers
# https://github.com/HackThisCode/FreeBSD-Helpers
#
# webhook rc.d script
# > For use with webhook: https://github.com/adnanh/webhook
#
# Version: 1.0.0
# Context: ANY                 Can be used in host OS or jails
# (Read more: https://hackthiscode.github.io/FreeBSD-Helpers/context/ )
#################################################################################
# MIT License
#
# Copyright (c) 2017 HackThisSite
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#################################################################################
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# webhook_enable (bool):       Set to NO by default.
#                              Set it to YES to enable webhook.
# webhook_flags (value):       Include other command-line arguments with this
#                              variable, such as -hooks or -verbose .
# webhook_user (value):        User to run webhook as. Set to www by default.
# webhook_cmd (value):         Set to /usr/local/bin/webhook by default.
#
#################################################################################

. /etc/rc.subr

name=webhook
procname=daemon
rcvar=${name}_enable

load_rc_config $name

: ${webhook_enable:="NO"}
: ${webhook_user="www"}
: ${webhook_flags=""}
: ${webhook_cmd="/usr/local/bin/${name}"}

command=${webhook_cmd}
command_args=${webhook_flags}
_piddir=/var/run/${name}
pidfile=${_piddir}/${name}.daemon.pid
pidfile_child=${_piddir}/${name}.child.pid
_logdir=/var/log/${name}
logfile=${_logdir}/${name}.log

start_precmd="${name}_prestart"
start_cmd="${name}_start"
reload_cmd="${name}_reload"
extra_commands="reload"

webhook_prestart() {
  install -d -o root -g wheel -m 755 ${_piddir}
  install -d -o root -g wheel -m 755 ${_logdir}
}

webhook_start() {
  /usr/sbin/daemon -P ${pidfile} -p ${pidfile_child} -u ${webhook_user} ${command} ${command_args} 2>&1 | tee -a ${logfile} &
}

webhook_reload() {
  /bin/kill -USR1 `cat ${pidfile_child}`
}

run_rc_command "$1"
