#!/usr/local/bin/bash
#
# Jail Control
#	v3.1 -- 01/22/2017
#		Added restart option
#	v3.0 -- 11/19/2016
#		Update for ezjail
#		Added help section
#	v2.0 -- 6/30/2012
#		Error correction and cleanup
# By: Kage (kage@hackthissite.org)
#
###

# Base path of ezjail configurations
EZJCFGDIR=/usr/local/etc/ezjail

# ezjail-admin command to run
EZJCMD=/usr/local/bin/ezjail-admin

###

if [ `id -u` != 0 ]; then
  echo "ERROR: You must be root to use this command."
  exit 1
fi

jailStartStop() {
  [ -z "$2" ] && echo "ERROR: No jail name specified" && exit 1
  ACTION=$1
  JAIL=$2
  [ ! -f "${EZJCFGDIR}/${JAIL}" ] && echo "ERROR: Jail does not exist" && exit 1
  $EZJCMD $ACTION $JAIL
}

if [ $# == 0 ]; then
  echo
  jls
  echo
  echo -n "Enter Jail ID: "
  read JID
  [ -z "${JID}" ] && exit
  OLDIFS=$IFS
  IFS="
"
  JLS=`jls | awk '{if($1 != "JID")print $1,$3}'`
  for jail in $JLS; do
    if [ `echo $jail | cut -d' ' -f1` == ${JID} ]; then
      IFS=$OLDIFS
      $EZJCMD console `echo ${jail} | cut -d' ' -f2`
      exit 0
    fi
  done
  IFS=$OLDIFS
  echo "ERROR: JID does not exist" && exit 1
else
  case $1 in
    start) jailStartStop start $2;;
    stop) jailStartStop stop $2;;
    restart) jailStartStop restart $2;;
    help)
      echo
      echo "USAGE: $0 [command <jailname>]"
      echo
      echo "This script allows you to either start, stop, or console into a"
      echo "FreeBSD jail using the ezjail system."
      echo
      echo "If run bare with no command, this will list all running jails and"
      echo "give the option to console into one."
      echo
      echo "COMMANDS:"
      echo
      echo "  start <jailname>      Starts a jail by <jailname>"
      echo
      echo "  stop <jailname>       Stops a jail by <jailname>"
      echo
      echo "  restart <jailname>    Stops then starts a jail by <jailname>"
      echo
      exit 0
      ;;
    * ) echo "ERROR: Invalid Command: $1" && exit 1;;
  esac
fi

### EOF
